openapi: 3.0.3
info:
  title: podGopher
  description: podGopher is a cms which manages multiple podcast shows.
  version: 1.0.0
servers:
  - description: Dev
    url: 'http://localhost:3000'

tags:
  - name: show
    description: A podcast show
  - name: episode
    description: A podcast episode which belongs to a podcast show
  - name: distribution
    description: Configuration of podcast rss feeds.
  - name: rss
    description: Available rss feeds

paths:
  /show:
    $ref: "./path/show.yaml#/show"
  /show/{showId}:
    $ref: "./path/show.yaml#/showId"

  /show/{showId}/episode:
    $ref: "./path/episode.yaml#/episode"
  /show/{showId}/episode/{episodeId}:
    $ref: "./path/episode.yaml#/episodeId"

  /show/{showId}/distribution:
    $ref: "./path/distribution.yaml#/distribution"
  /show/{showId}/distribution/{distributionId}:
    $ref: "./path/distribution.yaml#/distributionId"

  /rss/{showSlug}/{distributionSlug}:
    $ref: "./path/rss.yaml#/distributionSlug"